# This maps the Harness internal artifact variable to the .Values.image placeholder
image: <+artifact.image>

# You can also parameterize other things here if you want
replicas: 2
nameOverride: vibepad
